cmake_minimum_required(VERSION 3.20)
project(xdisk_all LANGUAGES CXX)

include(cmake/XdiskCommon.cmake)

add_subdirectory(xplatform)
add_subdirectory(LXMysql)
add_subdirectory(xdisk_pb)
add_subdirectory(register_client)
add_subdirectory(config_client)
add_subdirectory(xauth)
add_subdirectory(register_server)
add_subdirectory(config_server)
add_subdirectory(xlog)
add_subdirectory(xms_gateway)
add_subdirectory(xms_upload_service)
add_subdirectory(xms_download_service)
add_subdirectory(xms_dir_service)
add_subdirectory(xms_share_service)
add_subdirectory(xms_add_user)
add_subdirectory(config_gui)
add_subdirectory(xai_lib)
add_subdirectory(xms_disk_client_gui)
